name: Sync Hotfix to Dev

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  sync-hotfix-to-dev:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper branch merging

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Merge main into dev
        run: |
          git checkout dev
          git merge main --no-edit
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}