name: Release Main to Test and Dev on Hotfix Merge

on:
  push:
    branches:
      - main


jobs:
  release-to-test-and-dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history to access commit details
          token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for push permissions

      - name: Check if push is from a hotfix branch merge
        id: check-hotfix
        run: |
          # Get the commit message of the latest push to main
          COMMIT_SHA=${{ github.sha }}
          # Find the associated pull request for the commit
          PR_INFO=$(gh pr list --state merged --base main --limit 1 --json number,headRefName --jq '.[] | select(.headRefName | startswith("hotfix/"))')
          if [[ -n "$PR_INFO" ]]; then
            echo "Hotfix PR detected. Proceeding with release to test and dev."
            echo "is_hotfix=true" >> $GITHUB_OUTPUT
          else
            echo "No hotfix PR detected. Skipping release."
            echo "is_hotfix=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main into test branch
        if: steps.check-hotfix.outputs.is_hotfix == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout test
          git merge main --no-ff --no-edit
          git push origin test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main into dev branch
        if: steps.check-hotfix.outputs.is_hotfix == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout dev
          git merge main --no-ff --no-edit
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
