name: Create Pull Request from hotfix.1 to test

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed



jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Create pull request from hotfix.1 to test"
          title: "Hotfix: Merge hotfix.1 into test"
          body: |
            This pull request merges changes from the hotfix.1 branch into the test branch.
            Please review the changes and approve if everything looks good.
          branch: hotfix/hotfix1
          base: main
          labels: hotfix, needs-review