name: Enforce Release or Hotfix Branch for Pull Requests

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - test

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is a release or hotfix branch
        run: |
          if [[ "${{ github.head_ref }}" != release/* && "${{ github.head_ref }}" != hotfix/* ]]; then
            echo "Error: Pull requests to main or test must come from a branch matching 'release/*' or 'hotfix/*'."
            exit 1
          fi
