on:
  # workflow_dispatch: changed to manual
  push:
    branches:
    - dev

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # environment: dev
    steps:
    - uses: actions/checkout@v3
    
# Installs Node and the npm packages saved in your package.json file in the build
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 18.x
        
    - name: install ADF Utilities package
      run: npm install
      working-directory: ${{github.workspace}}/ADFROOT/build  # (1) provide the folder location of the package.json file
        
# Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
    - name: Validate
      run: npm run build validate ${{github.workspace}}/ADFROOT/ /subscriptions/6aba5050-d861-4b6d-a2f7-3f5db5562c71/resourceGroups/tony-min/providers/Microsoft.DataFactory/factories/adf-cimicgittest-prod # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 
      working-directory: ${{github.workspace}}/ADFROOT/build
 

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}}/ADFROOT/ /subscriptions/6aba5050-d861-4b6d-a2f7-3f5db5562c71/resourceGroups/tony-min/providers/Microsoft.DataFactory/factories/adf-cimicgittest-prod "ExportedArmTemplate"  # (3) The build command, as validate, needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance. The 3rd parameter is the exported ARM template artifact name 
      working-directory: ${{github.workspace}}/ADFROOT/build
 
# In order to leverage the artifact in another job, we need to upload it with the upload action 
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExportedArmTemplate # (4) use the same artifact name you used in the previous export step
        path: ${{github.workspace}}/ADFROOT/build/ExportedArmTemplate
        
  release:
    needs: build
    runs-on: ubuntu-latest
    # environment: dev  # Specify the dev environment
    steps:
    
      - uses: actions/checkout@v3
 # we 1st download the previously uploaded artifact so we can leverage it later in the release job     
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate # (5) Artifact name 
          
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: tony-min 
          template: ARMTemplateForFactory.json 
          parameters: ADFROOT/prodParameters/cgParameters.json
          deploymentMode: incremental
          # skipAzModuleInstallation:  # Parameters which skip the Az module installation. Optional, default is false.      
